services:
  app:
    build: .
    ports:
      - "3000:3000"
    shm_size: '1gb'
    environment:
      - PORT=3000
      - API_KEY=
      - NODE_ENV=production
      - PUPPETEER_HEADLESS=true
    restart: unless-stopped