name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build and push Docker image
      uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          ${{ env.ARTIFACTORY_REGISTRY }}/${{ env.ARTIFACTORY_REPOSITORY }}/${{ env.ARTIFACT }}:latest
          ${{ env.ARTIFACTORY_REGISTRY }}/${{ env.ARTIFACTORY_REPOSITORY }}/${{ env.ARTIFACT }}:${{ env.VERSION }}
          ${{ env.GCLOUD_REGISTRY }}/${{ env.GCLOUD_REPOSITORY }}/${{ env.ARTIFACT }}:latest
          ${{ env.GCLOUD_REGISTRY }}/${{ env.GCLOUD_REPOSITORY }}/${{ env.ARTIFACT }}:${{ env.VERSION }}
